import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRef } from 'react'

const inter = Inter({ subsets: ['latin'], weight: '400' })

export default function Home() {
  const secondSection: any = useRef(null)

  function scrollToSecondSection() {
    secondSection.current!.scrollIntoView({ behavior: 'smooth' })
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className + ' bg-background-light'}>
        <section
          id="intro"
          className="flex min-h-screen w-full items-center justify-center flex-col"
        >
          <div>
            <p className="inline-flex items-center gap-2 text-2xl text-tertiary">
              About me & other things I do
              <span>
                <svg
                  aria-hidden="true"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                  className="w-6 h-6"
                >
                  <path
                    d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  ></path>
                </svg>
              </span>
              <span>
                <Link
                  href="#"
                  className="group text-sky-600 transition duration-300"
                >
                  See more
                  <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-sky-600"></span>
                </Link>
              </span>
            </p>
            <p className="text-5xl font-medium">Dennis Moes,</p>
            <p className="text-2xl text-tertiary-light">
              Wannabe movie critic & software engineer
            </p>
          </div>
          <button
            onClick={scrollToSecondSection}
            className="mt-8 p-4 bg-primary-light rounded-xl animate-wiggle"
          >
            <svg
              aria-hidden="true"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
              className="w-4 h-4"
            >
              <path
                d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              ></path>
            </svg>
          </button>
        </section>
        <section id="short-bio" className="min-h-screen" ref={secondSection}>
          <div className="max-w-3xl mx-auto">
            <div className="flex flex-row gap-2 w-full">
              <div className="w-2/3 bg-primary-light p-4 rounded-xl">
                <p className="text-3xl">Hello, nice to meet you!</p>
                <p className="text-tertiary-light">
                  Who am I? I&apos;m your overly excited student who wants to
                  conquer the world with his developing coding skills by making
                  the next big thing. Also a bit to ambitious sometimes.
                </p>
                <Link
                  href="#"
                  className="mt-4 inline-flex flex-row items-center py-2 w-full justify-center rounded-md bg-secondary-light text-primary-light"
                >
                  Keep reading my bio{' '}
                  <svg
                    aria-hidden="true"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-4 h-4"
                  >
                    <path
                      d="M8.25 4.5l7.5 7.5-7.5 7.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    ></path>
                  </svg>
                </Link>
              </div>
              <div className="w-1/3 bg-red-200">
                <p>Hello</p>
              </div>
            </div>
          </div>
        </section>
        <section id="toolbox">
          <div className="max-w-3xl mx-auto">
            <p>My toolbox</p>
          </div>
        </section>
      </main>
    </>
  )
}
